import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="m-auto py-[10%] w-[500px] h-[500px]">
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Header />
          <div className="items-center text-center justify-between w-[450px] h-[200px] m-auto">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
